# Site Settings
title: "Migration & Modernization"
description: "AI-powered tools and techniques for application modernization"
url: "https://tsanders-rh.github.io"
baseurl: ""
repository: "tsanders-rh/tsanders-rh.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Author
author:
  name: "Todd Sanders"
  avatar: "/assets/images/avatar.jpg" # Optional: add your photo later
  bio: "Application modernization, migration automation, and AI tooling"
  location: "Remote"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tsanders-rh"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tsanders-rh.github.io"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tsanders-rh"

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/

# Reading Files
include:
  - _pages

# Exclude from processing
exclude:
  - README.md
  - DEPLOYMENT.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: false
      toc_sticky: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Comments (optional - uncomment to enable)
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "your-disqus-shortname"

# Analytics (optional - uncomment to enable)
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
#     anonymize_ip: false
